# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: beit3service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62\x65it3service.proto\x12\x0c\x62\x65it3service\"O\n\x0c\x42\x65it3Request\x12\x19\n\x11serialized_tensor\x18\x01 \x01(\x0c\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x12\n\ntracker_id\x18\x03 \x01(\t\" \n\rBeit3Response\x12\x0f\n\x07retcode\x18\x01 \x01(\t2V\n\x0c\x42\x65it3Service\x12\x46\n\x0b\x45nqueueItem\x12\x1a.beit3service.Beit3Request\x1a\x1b.beit3service.Beit3Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'beit3service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BEIT3REQUEST']._serialized_start=36
  _globals['_BEIT3REQUEST']._serialized_end=115
  _globals['_BEIT3RESPONSE']._serialized_start=117
  _globals['_BEIT3RESPONSE']._serialized_end=149
  _globals['_BEIT3SERVICE']._serialized_start=151
  _globals['_BEIT3SERVICE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
